language: node_js
node_js:
  - '8'
  - '10'
branches:
  only:
    - master
cache:
  directories:
    - node_modules
install:
 - npm install
script:
  - tsc -p .
  - npm t
after_script:
  - cat coverage/lcov.info | coveralls && rm -rf ./coverage
notifications:
  email:
    on_success: never
    on_failure: always